server:
  port: 0
  
spring:  application:
    name: order-service
    
  h2:    console:      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
     url: jdbc:mariadb://localhost:3306/mydb
     driver-class-name: org.mariadb.jdbc.Driver
     username: root
     password: test1234
    
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        
eureka:
  instance:    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}${server.port}  client:    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone: http://127.0.0.1:8761/eureka

logging:
  level:    com.example.orderservice: DEBUG
