server:
  port: 8888
  
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/youjaewoong/spring-msa/tree/Configuratin-Service/git-local-repo